-- MySQL Script generated by MySQL Workbench
-- Sat May 16 16:29:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reservas_hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `reservas_hotel` ;

-- -----------------------------------------------------
-- Schema reservas_hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reservas_hotel` DEFAULT CHARACTER SET utf8mb4 ;
USE `reservas_hotel` ;

-- -----------------------------------------------------
-- Table `reservas_hotel`.`TIPO_HABITACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`TIPO_HABITACION` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`TIPO_HABITACION` (
  `id_Tipo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('Sencilla', 'Doble', 'Triple', 'Suite') NOT NULL,
  `capacidad_Max` TINYINT NOT NULL,
  `numero_Camas` TINYINT NOT NULL,
  `precioBaseNoche` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id_Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`ROL` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`ROL` (
  `id_Rol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('Administrador', 'Recepcionista', 'Personal_Limpieza') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id_Rol`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `reservas_hotel`.`ROL` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`HUESPED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`HUESPED` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`HUESPED` (
  `id_Huesped` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `tipo_Documento` ENUM('CC', 'CE', 'PA') NOT NULL,
  `numero_Documento` VARCHAR(20) NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  `fecha_Nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id_Huesped`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `uk_huesped_documento` ON `reservas_hotel`.`HUESPED` (`tipo_Documento` ASC, `numero_Documento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`EMPLEADO` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`EMPLEADO` (
  `id_Empleado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_documento` VARCHAR(20) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `id_Rol` INT UNSIGNED NOT NULL,
  `id_Supervisor` INT UNSIGNED NULL,
  PRIMARY KEY (`id_Empleado`),
  CONSTRAINT `fk_empleado_rol`
    FOREIGN KEY (`id_Rol`)
    REFERENCES `reservas_hotel`.`ROL` (`id_Rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleado_supervisor`
    FOREIGN KEY (`id_Supervisor`)
    REFERENCES `reservas_hotel`.`EMPLEADO` (`id_Empleado`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_EMPLEADO_ROL1_idx` ON `reservas_hotel`.`EMPLEADO` (`id_Rol` ASC) VISIBLE;

CREATE INDEX `fk_empleado_supervisor_idx` ON `reservas_hotel`.`EMPLEADO` (`id_Supervisor` ASC) VISIBLE;

CREATE UNIQUE INDEX `numero_documento_UNIQUE` ON `reservas_hotel`.`EMPLEADO` (`numero_documento` ASC) VISIBLE;

CREATE UNIQUE INDEX `usuario_UNIQUE` ON `reservas_hotel`.`EMPLEADO` (`usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`HABITACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`HABITACION` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`HABITACION` (
  `id_Habitacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NOT NULL,
  `piso` TINYINT UNSIGNED NOT NULL,
  `estado` ENUM('Disponible', 'Reservada', 'Ocupada', 'En_Limpieza', 'En_Mantenimiento') NOT NULL,
  `id_Tipo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Habitacion`),
  CONSTRAINT `fk_habitacion_tipo`
    FOREIGN KEY (`id_Tipo`)
    REFERENCES `reservas_hotel`.`TIPO_HABITACION` (`id_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `codigo_UNIQUE` ON `reservas_hotel`.`HABITACION` (`codigo` ASC) VISIBLE;

CREATE INDEX `fk_HABITACION_TIPO_HABITACION1_idx` ON `reservas_hotel`.`HABITACION` (`id_Tipo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`CLIENTE` (
  `id_Cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_Registro` DATETIME NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`PERSONA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`PERSONA` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`PERSONA` (
  `id_Cliente` INT UNSIGNED NOT NULL,
  `tipo_Documento` ENUM('CC', 'CE', 'PA') NOT NULL,
  `numero_Documento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `fecha_Nacimiento` DATE NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Cliente`),
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `reservas_hotel`.`CLIENTE` (`id_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `uk_persona_documento` ON `reservas_hotel`.`PERSONA` (`tipo_Documento` ASC, `numero_Documento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`EMPRESA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`EMPRESA` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`EMPRESA` (
  `id_Cliente` INT UNSIGNED NOT NULL,
  `nit` VARCHAR(20) NOT NULL,
  `razon_Social` VARCHAR(150) NOT NULL,
  `representante_Legal` VARCHAR(200) NOT NULL,
  `sector_Economico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Cliente`),
  CONSTRAINT `fk_empresa_cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `reservas_hotel`.`CLIENTE` (`id_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nit_UNIQUE` ON `reservas_hotel`.`EMPRESA` (`nit` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`CONTACTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`CONTACTO` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`CONTACTO` (
  `id_Contacto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_Contacto` ENUM('Telefono_Fijo', 'Telefono_Movil', 'Correo_Electronico') NOT NULL,
  `valor` VARCHAR(150) NOT NULL,
  `es_Principal` TINYINT(1) NOT NULL,
  `id_Cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Contacto`),
  CONSTRAINT `fk_contacto_cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `reservas_hotel`.`CLIENTE` (`id_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_contacto_cliente_idx` ON `reservas_hotel`.`CONTACTO` (`id_Cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`DIRECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`DIRECCION` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`DIRECCION` (
  `id_Direccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_Direccion` ENUM('Residencia', 'Facturacion') NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `ciudad` VARCHAR(80) NOT NULL,
  `departamento` VARCHAR(80) NOT NULL,
  `codigo_Postal` VARCHAR(10) NULL,
  `pais` VARCHAR(50) NOT NULL,
  `es_Principal` TINYINT(1) NOT NULL,
  `id_Cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Direccion`),
  CONSTRAINT `fk_direccion_cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `reservas_hotel`.`CLIENTE` (`id_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_direccion_cliente_idx` ON `reservas_hotel`.`DIRECCION` (`id_Cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`RESERVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`RESERVA` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`RESERVA` (
  `id_Reserva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `canal` ENUM('Telefonica', 'Presencial') NOT NULL,
  `fecha_Creacion` DATETIME NOT NULL,
  `fechaCheckInPrevista` DATETIME NOT NULL,
  `fechaCheckOutPrevista` DATETIME NOT NULL,
  `estado` ENUM('Pendiente', 'Confirmada', 'En_Curso', 'Finalizada', 'Cancelada', 'No_Show') NOT NULL,
  `precio_Total` DECIMAL(15,2) NOT NULL,
  `id_Cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Reserva`),
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `reservas_hotel`.`CLIENTE` (`id_Cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_reserva_cliente_idx` ON `reservas_hotel`.`RESERVA` (`id_Cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`RESERVA_HABITACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`RESERVA_HABITACION` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`RESERVA_HABITACION` (
  `id_Reserva` INT UNSIGNED NOT NULL,
  `id_Habitacion` INT UNSIGNED NOT NULL,
  `numero_huespedes` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Reserva`, `id_Habitacion`),
  CONSTRAINT `fk_reservahab_reserva`
    FOREIGN KEY (`id_Reserva`)
    REFERENCES `reservas_hotel`.`RESERVA` (`id_Reserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservahab_habitacion`
    FOREIGN KEY (`id_Habitacion`)
    REFERENCES `reservas_hotel`.`HABITACION` (`id_Habitacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_reservahab_habitacion_idx` ON `reservas_hotel`.`RESERVA_HABITACION` (`id_Habitacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`PAGO` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`PAGO` (
  `id_Pago` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `medio` ENUM('Tarjeta_Credito', 'Tarjeta_Debito', 'Efectivo', 'Transferencia_Bancaria') NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `estado` ENUM('Pendiente', 'Aprobado', 'Rechazado', 'Reversado') NOT NULL,
  `fecha` DATETIME NOT NULL,
  `id_Reserva` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Pago`),
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`id_Reserva`)
    REFERENCES `reservas_hotel`.`RESERVA` (`id_Reserva`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_pago_reserva_idx` ON `reservas_hotel`.`PAGO` (`id_Reserva` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`ASIGNACION_HUESPED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`ASIGNACION_HUESPED` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`ASIGNACION_HUESPED` (
  `id_Huesped` INT UNSIGNED NOT NULL,
  `id_Reserva` INT UNSIGNED NOT NULL,
  `id_Habitacion` INT UNSIGNED NOT NULL,
  `es_Titular` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_Huesped`, `id_Reserva`, `id_Habitacion`),
  CONSTRAINT `fk_asignacion_huesped`
    FOREIGN KEY (`id_Huesped`)
    REFERENCES `reservas_hotel`.`HUESPED` (`id_Huesped`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_asignacion_reservahab`
    FOREIGN KEY (`id_Reserva` , `id_Habitacion`)
    REFERENCES `reservas_hotel`.`RESERVA_HABITACION` (`id_Reserva` , `id_Habitacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_asignacion_reservahab_idx` ON `reservas_hotel`.`ASIGNACION_HUESPED` (`id_Reserva` ASC, `id_Habitacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`EVENTO_RESERVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`EVENTO_RESERVA` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`EVENTO_RESERVA` (
  `id_Evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_Hora` DATETIME NOT NULL,
  `id_Reserva` INT UNSIGNED NOT NULL,
  `id_Empleado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Evento`),
  CONSTRAINT `fk_evento_reserva`
    FOREIGN KEY (`id_Reserva`)
    REFERENCES `reservas_hotel`.`RESERVA` (`id_Reserva`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evento_empleado`
    FOREIGN KEY (`id_Empleado`)
    REFERENCES `reservas_hotel`.`EMPLEADO` (`id_Empleado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_evento_reserva_idx` ON `reservas_hotel`.`EVENTO_RESERVA` (`id_Reserva` ASC) VISIBLE;

CREATE INDEX `fk_evento_empleado_idx` ON `reservas_hotel`.`EVENTO_RESERVA` (`id_Empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`CANCELACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`CANCELACION` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`CANCELACION` (
  `id_Evento` INT UNSIGNED NOT NULL,
  `motivo` TEXT NOT NULL,
  `penalizacion` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_Evento`),
  CONSTRAINT `fk_cancelacion_evento`
    FOREIGN KEY (`id_Evento`)
    REFERENCES `reservas_hotel`.`EVENTO_RESERVA` (`id_Evento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`SOLICITUD_REEMBOLSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`SOLICITUD_REEMBOLSO` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`SOLICITUD_REEMBOLSO` (
  `id_Solicitud` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `motivo` TEXT NOT NULL,
  `estado` ENUM('Pendiente', 'Aprobado', 'Procesado', 'Rechazado') NOT NULL,
  `medio` ENUM('Tarjeta_Credito', 'Tarjeta_Debito', 'Efectivo', 'Transferencia_Bancaria') NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `fecha_Procesamiento` DATETIME NULL,
  `id_Cancelacion` INT UNSIGNED NOT NULL,
  `id_Empleado` INT UNSIGNED NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_Solicitud`),
  CONSTRAINT `fk_solicitud_empleado`
    FOREIGN KEY (`id_Empleado`)
    REFERENCES `reservas_hotel`.`EMPLEADO` (`id_Empleado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitud_cancelacion`
    FOREIGN KEY (`id_Cancelacion`)
    REFERENCES `reservas_hotel`.`CANCELACION` (`id_Evento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_Cancelacion_UNIQUE` ON `reservas_hotel`.`SOLICITUD_REEMBOLSO` (`id_Cancelacion` ASC) VISIBLE;

CREATE INDEX `fk_solicitud_empleado_idx` ON `reservas_hotel`.`SOLICITUD_REEMBOLSO` (`id_Empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`CHECK_IN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`CHECK_IN` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`CHECK_IN` (
  `id_Evento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Evento`),
  CONSTRAINT `fk_checkin_evento`
    FOREIGN KEY (`id_Evento`)
    REFERENCES `reservas_hotel`.`EVENTO_RESERVA` (`id_Evento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservas_hotel`.`CHECK_OUT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas_hotel`.`CHECK_OUT` ;

CREATE TABLE IF NOT EXISTS `reservas_hotel`.`CHECK_OUT` (
  `id_Evento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Evento`),
  CONSTRAINT `fk_checkout_evento`
    FOREIGN KEY (`id_Evento`)
    REFERENCES `reservas_hotel`.`EVENTO_RESERVA` (`id_Evento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
