# Puerto del servidor
server.port=8080

# Nombre de la app
spring.application.name=proyecto-bd1

# BD temporal H2 en memoria (se reemplazara por MySQL cuando este listo)
spring.datasource.url=jdbc:h2:mem:tempdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
